services:
  app:
    build:
      context: .
      args:
        - FLAG=flag{test_flag_placeholder}
    ports:
      - "80:80"
      - "8001:8001"
      - "8002:8002"
    expose:
      - 80
      - 8001
      - 8002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 5s
      retries: 5
      interval: 10s
